source 'https://github.com/CocoaPods/Specs.git'

target 'DTObservable', :exclusive => true do
  pod "DTObservable", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "DTObservable", :path => "../"

  
end
